### ISSUE TITLE
Does not work with new restructed libs from Adafruit

### ISSUE THREAD

**Issue by miki89** [mattdy/python-lis3dh#4]
Hi Matt, 

great work! It helped me a lot! 

But unfortunately there are small issues with the new restructured gpio/i2c libs from Adafruit. 

There were 3 changes required to get it working for me:
in file LIS3DH.py: 
a) line15: The import must be changed from `from Adafruit_I2C import Adafruit_I2C` to `import Adafruid_GPIO.I2C as I2C`
b) line 94: further the instanciaton from `self.i2c = Adafruit_I2C(address, busnum=bus)` to `self.i2c = I2C.Device(address, busnum=bus)`

in file testLIS3DH.py
c) line 16: the init of the sensor object need the bus number: `sensor = LIS3DH(debug=True)` to `sensor = LIS3DH(bus=1,debug=True)`

Thank you!
Best Regards

Michael

**Comment by mattdy** [comment]
Hi Michael,

Thanks for that - I hadn't noticed that Adafruit had changed their libraries. Would you be able to submit a change request with these adaptations? I don't have access to my LIS3DHs at the moment to test, and would prefer to give you credit for doing the work!

Cheers,
Matt

**Comment by RichardBronosky** [comment]
Whatever came of this? In your opinion, would you recommend this sensor to someone targeting Python on RPi who has not yet made a purchase?

**Comment by mattdy** [comment]
@RichardBronosky - This issue is still unresolved, the library requires updating for the repackaged Adafruit libraries.

That said, it shouldn't be too difficult to update (only a few changes as above), so would definitely recommend the sensor, and hopefully this library will work for you!

**Comment by holzfigure** [comment]
I filed a pull request that incorporates the changes in demand (i did it slightly differently than how @miki89 proposed, but it does essentially the same). It works perfectly: I am working with these accelerometers a lot, so i consider the submitted code rather well-tested. @RichardBronosky: I can definitely recommend buying that sensor and using it on the Pi (you can even use 2 on a single Pi since you can select a second I²C  address) with @mattdy s library (and my updates,).

**Comment by mattdy** [comment]
This has been resolved in #5. Thanks!
